#Configuración del sitio
title: Michael Andrés Murcia
email: mamurciac@unal.edu.co
url: https://mamurciac.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
keywords: "your keywords, separated by commas"
keywords: "Cálculo, Datos, Información, Ingeniería, Programación, Sistemas, Ilustración Digital"
skills: "Web Developer - Graphic Artist - User Experience Designer"
meta_author: Michael Andrés Murcia Contreras
meta_email: mamurciac@unal.edu.co

#Verificación de la página en el buscador de Google (Con Google Webmaster Tools)
google_verify:

#Verificación de la página en el buscador de Bing. Enlace de apoyo: https://ssl.bing.com/webmaster/configure/verify/ownership Option 2
bing_verify:

#Formulario de Contacto:
#  - static: Se valida el envió del mensaje de correo electrónico con Formspree.io
#  - disqus: Se reemplaza el formulario de contacto por el hilo de Disqus
#Para mantener el formulario de contacto de PHP predeterminado, se comenta la próxima línea
contact: static

#Si se utiliza disqus, es necesario el nombre breve de la página en disqus
#https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

#Ajustes de Color (En codificación hexadecimal sin la etiqueta de hashtag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

#Ajustes de pie de página
footer:
  copyright: El conocimiento es la mejor inversión que se puede hacer (Abraham Lincoln)
  location: Ubicación
  social: En la Web
  credits: Créditos

#Nombres de usuario para Redes Sociales (Hay varias disponibles como: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/maykol.murziia.fiifty/
  - title: instagram
    url: https://www.instagram.com/mamurciac/
  - title: linkedin
    url: https://www.linkedin.com/in/michael-andr%C3%A9s-murcia-contreras-05428b147/
  - title: github
    url: http://github.com/mamurciac/
  - title: google-plus
    url: https://plus.google.com/112959156376505048233/

#Dirección Postal (Se pueden añadir cuantas líneas sean necesarias)
address:
  - line: Universidad Nacional
  - line: Bogotá D.C., Colombia

#Contenido de los créditos
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

#Ajustes de compilación
markdown: kramdown
permalink: pretty
